flags: {}
packages:
    - ./ihaskell
    - ./ihaskell/ipython-kernel
    - ./ihaskell/ghc-parser
    - ./ihaskell/ihaskell-display/ihaskell-aeson
    - ./ihaskell/ihaskell-display/ihaskell-blaze
    - ./ihaskell/ihaskell-display/ihaskell-charts
    - ./ihaskell/ihaskell-display/ihaskell-diagrams
    - ./ihaskell/ihaskell-display/ihaskell-gnuplot
    - ./ihaskell/ihaskell-display/ihaskell-hatex
    - ./ihaskell/ihaskell-display/ihaskell-juicypixels
    - ./ihaskell/ihaskell-display/ihaskell-magic
    - ./ihaskell/ihaskell-display/ihaskell-plot
    - ./ihaskell/ihaskell-display/ihaskell-static-canvas
#    - ./ihaskell/ihaskell-display/ihaskell-widgets
    - ./stochaskell
resolver: lts-12.26
allow-newer: true
extra-deps:
- Chart-1.9
- Chart-cairo-1.9
- lazy-csv-0.5.1
- magic-1.1
- plot-0.2.3.9
- plots-0.1.0.2
