resolver: lts-12.26
packages:
- stochaskell
extra-deps:
- Chart-1.9
- Chart-cairo-1.9
- lazy-csv-0.5.1
- magic-1.1
- plot-0.2.3.9
- plots-0.1.0.2
- github: gibiansky/IHaskell
  commit: 910119f65f52f327f0305d432740d62aa9f50a2e
  subdirs:
  - .
  - ipython-kernel
  - ghc-parser
  - ihaskell-display/ihaskell-aeson
  - ihaskell-display/ihaskell-blaze
  - ihaskell-display/ihaskell-charts
  - ihaskell-display/ihaskell-diagrams
  - ihaskell-display/ihaskell-gnuplot
  - ihaskell-display/ihaskell-hatex
  - ihaskell-display/ihaskell-juicypixels
  - ihaskell-display/ihaskell-magic
  - ihaskell-display/ihaskell-plot
  - ihaskell-display/ihaskell-static-canvas
  - ihaskell-display/ihaskell-widgets
