name: stochaskell
version: '1.0.0'
synopsis: A probabilistic programming language
description: An embedded domain-specific language for specifying probabilistic
  programs that can be compiled to multiple existing probabilistic programming
  languages.
category: Language
author: David A Roberts
maintainer: d@vidr.cc
copyright: 2015-2019 David A Roberts
license: GPL-3
github: davidar/stochaskell
homepage: https://davidar.github.io/stochaskell
dependencies:
- array
- base >=4.10 && <5
- bimap
- binary
- Boolean
- bytestring
- cassava
- Chart
- Chart-cairo
- containers
- cryptohash
- data-binary-ieee754
- deepseq
- diagrams-cairo
- diagrams-core
- diagrams-lib
- directory
- extra
- generic-data
- hmatrix
- lazy-csv
- logfloat
- math-functions
- MissingH
- mtl
- plots
- process
- random
- random-fu
- recursion-schemes
- silently
- split
- statistics
- temporary
- time
- utility-ht
- vector
library:
  source-dirs: src
  exposed-modules:
  - Language.Church
  - Language.Edward
  - Language.Graphviz
  - Language.PyMC3
  - Language.Stan
  - Language.Stochaskell
  - Language.Stochaskell.Expression
  - Language.Stochaskell.Plot
  - Language.Stochaskell.Prelude
