flags: {}
extra-package-dbs: []
packages:
- .
- ./app
- ./standalone-haddock
system-ghc: false
extra-deps:
- cairo-0.13.6.0
- Chart-cairo-1.9.1
- diagrams-cairo-1.4.1
- glib-0.13.7.1
- gtk2hs-buildtools-0.13.5.0
- lazy-csv-0.5.1
- pango-0.13.6.1
- plots-0.1.1.2
resolver: lts-13.26
