name: stochaskell-exes
dependencies:
- base >=4.10 && <5
- directory
- stochaskell
executables:
  autostat-exe:
    main: Main.hs
    source-dirs: autostat
  benchmark-exe:
    main: Main.hs
    source-dirs: benchmark
  cp-exe:
    main: Main.hs
    source-dirs: cp
  dp-exe:
    main: Main.hs
    source-dirs: dp
  mgp-exe:
    main: Main.hs
    source-dirs: mgp
  poly-exe:
    main: Main.hs
    source-dirs: poly
  rj-exe:
    main: Main.hs
    source-dirs: rj
  sgcp-exe:
    main: Main.hs
    source-dirs: sgcp
  ssgcp-exe:
    main: Main.hs
    source-dirs: ssgcp
